export const temporaryBoardData = [
    { row: 0, col: 0 },
    { row: 0, col: 1, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 0, col: 2 },
    { row: 0, col: 3, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 0, col: 4 },
    { row: 0, col: 5, piece: { direction: "DOWNWARDS", type: "KING" } },
    { row: 0, col: 6 },
    { row: 0, col: 7, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 1, col: 0, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 1, col: 1 },
    { row: 1, col: 2, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 1, col: 3 },
    { row: 1, col: 4, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 1, col: 5 },
    { row: 1, col: 6, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 1, col: 7 },
    { row: 2, col: 0 },
    { row: 2, col: 1, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 2, col: 2 },
    { row: 2, col: 3, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 2, col: 4 },
    { row: 2, col: 5, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 2, col: 6 },
    { row: 2, col: 7, piece: { direction: "DOWNWARDS", type: "REGULAR" } },
    { row: 3, col: 0 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 3, col: 5 },
    { row: 3, col: 6 },
    { row: 3, col: 7 },
    { row: 4, col: 0 },
    { row: 4, col: 1 },
    { row: 4, col: 2 },
    { row: 4, col: 3 },
    { row: 4, col: 4 },
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 4, col: 7 },
    { row: 5, col: 0, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 5, col: 1 },
    { row: 5, col: 2, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 5, col: 3 },
    { row: 5, col: 4, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 5, col: 5 },
    { row: 5, col: 6, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 5, col: 7 },
    { row: 6, col: 0 },
    { row: 6, col: 1, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 6, col: 2 },
    { row: 6, col: 3, piece: { direction: "UPWARDS", type: "KING" } },
    { row: 6, col: 4 },
    { row: 6, col: 5, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 6, col: 6 },
    { row: 6, col: 7, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 7, col: 0, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 7, col: 1 },
    { row: 7, col: 2, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 7, col: 3 },
    { row: 7, col: 4, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 7, col: 5 },
    { row: 7, col: 6, piece: { direction: "UPWARDS", type: "REGULAR" } },
    { row: 7, col: 7 },
];
